Repository Source-Pocket/source-pocket, pull requests merged in 2020-12, with the labels that each got.

#16 Github issue & pr templates and Contributing guides
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: enhancement

#17 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: refactor

#18 Create CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#23 Merging
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: enhancement, refactor

#25 feat: added auto-assign bot
  .github/auto_assign.yml
Labels: PR: reviewed-approved

#21 Update README.md
  README.md
Labels: PR: reviewed-approved

#27 fix: deleted auto_assign.yml
  .github/CODEOWNERS
  .github/auto_assign.yml
Labels: PR: reviewed-approved

#28 fix: merging dev branch
  .github/CODEOWNERS
  README.md
Labels: PR: unreviewed

#30 feat: development tools pocket added
  docs/android-studio.md
  docs/aws.md
  docs/azure.md
  docs/docker.md
  docs/git.md
  docs/visual-studio-code.md
  docs/visualstudio.md
  docusaurus.config.js
  sidebars.js
Labels: PR: partially-approved

#31 docs: seperated to titles
  docs/front-end.md
Labels: PR: partially-approved

#34 feat: Operating Systems Pocket added
  docs/gnu-linux.md
  docs/macos.md
  docs/windows.md
  docusaurus.config.js
  sidebars.js
Labels: PR: unreviewed

#35 feat: mobile development pocket added
  docs/android.md
  docs/flutter.md
  docs/ios.md
  docs/reactnative.md
  docs/xamarin.md
  docusaurus.config.js
  sidebars.js
Labels: PR: partially-approved

#36 Update frontend.md
  docs/front-end.md
Labels: PR: unreviewed

#38 #14 all titles migrated
  docs/artificial-intelligence/artificial-intelligence.md
  docs/artificial-intelligence/computer-vision.md
  docs/artificial-intelligence/deep-learning.md
  docs/artificial-intelligence/machine-learning.md
  docs/artificial-intelligence/other.md
  docs/artificial-intelligence/resources.md
  docs/data-science/big-data.md
  docs/data-science/other.md
  docs/data-science/statistical-learning.md
  docs/databases/mongodb.md
  docs/databases/mssql.md
  docs/databases/mysql.md
  docs/databases/other.md
  docs/databases/postgresdb.md
  docs/databases/sql-tsql-plsql.md
  docs/embedded-systems/arduino.md
  docs/embedded-systems/arm.md
  docs/embedded-systems/other.md
  docs/embedded-systems/raspberry-pi.md
  docs/game-development/other.md
  docs/game-development/unity.md
  docs/game-development/unreal-engine.md
  docs/graphic-design/general-design.md
  docs/graphic-design/illustrations.md
  docs/graphic-design/misc-design.md
  docs/graphic-design/motion-design.md
  docs/graphic-design/other.md
  docs/graphic-design/photo-and-video.md
  docs/graphic-design/sound-design.md
  docs/graphic-design/ui-ux-design.md
  docs/network-programming/ipv4-ipv6.md
  docs/network-programming/network.md
  docs/network-programming/tcpip.md
  docusaurus.config.js
  sidebars.js
Labels: PR: reviewed-approved
