Repository Source-Pocket/source-pocket, pull requests merged in 2021-04, with the labels that each got.

#169 [#168] feat: implement DocSearch
  .gitignore
  docusaurus.config.js
  src/css/custom.css
Labels: PR: reviewed-approved, documentation, enhancement

#170 Dev to Main 🚢🚢
  .gitignore
  docs/development-tools/docker.md
  docs/programming-languages/csharp.md
  docusaurus.config.js
  src/css/custom.css
Labels: PR: unreviewed, dev-to-main, documentation, enhancement

#171 docs: add wizard zines website
  docs/operating-systems/gnu-linux.md
Labels: PR: partially-approved

#173 docs: add Essential Go source
  docs/programming-languages/go.md
Labels: PR: partially-approved

#174 Dev to Main 🚢
  docs/operating-systems/gnu-linux.md
  docs/programming-languages/csharp.md
  docs/programming-languages/go.md
Labels: PR: unreviewed, bug, dev-to-main, documentation

#175 docs: add C# resources
  docs/programming-languages/csharp.md
Labels: PR: partially-approved, documentation

#176 docs: added linux link
  docs/operating-systems/gnu-linux.md
Labels: PR: partially-approved

#177 docs: added links to many section
  docs/programming-languages/csharp.md
  docs/programming-languages/go.md
  docs/web-development/angularjs.md
  docs/web-development/asp-net-mvc.md
  docs/web-development/jquery.md
  docs/web-development/netcore.md
  docs/web-development/nodejs.md
  docs/web-development/reactjs.md
Labels: PR: partially-approved

#178 Dev to Main 🚢
  docs/operating-systems/gnu-linux.md
  docs/programming-languages/csharp.md
  docs/programming-languages/go.md
  docs/web-development/angularjs.md
  docs/web-development/asp-net-mvc.md
  docs/web-development/jquery.md
  docs/web-development/netcore.md
  docs/web-development/nodejs.md
  docs/web-development/reactjs.md
Labels: PR: unreviewed, dev-to-main, documentation

#180 Update javascript.md
  docs/web-development/javascript.md
Labels: PR: partially-approved

#179 docs: added links to many section
  docs/graphic-design/general-design.md
  docs/graphic-design/illustrations.md
  docs/programming-languages/assembly.md
  docs/programming-languages/csharp.md
  docs/programming-languages/r.md
  docs/web-development/hosting-and-servers.md
Labels: PR: unreviewed

#181 Dev to Main 🚢
  docs/graphic-design/general-design.md
  docs/graphic-design/illustrations.md
  docs/programming-languages/assembly.md
  docs/programming-languages/csharp.md
  docs/programming-languages/r.md
  docs/programming-languages/swift.md
  docs/web-development/hosting-and-servers.md
  docs/web-development/javascript.md
Labels: PR: unreviewed, dev-to-main, documentation

#184 Update python.md
  docs/programming-languages/python.md
Labels: PR: partially-approved
