Repository Source-Pocket/source-pocket, pull requests merged in 2021-02, with the labels that each got.

#44 fix: security update
  package.json
  yarn.lock
Labels: PR: unreviewed

#43 docs: add link and customize titles
  docs/web-development/nodejs.md
Labels: PR: reviewed-approved

#46 docs: add contribution guide and edit style of code
  docs/contribution-guide.md
  docs/web-development/angularjs.md
  docs/web-development/nodejs.md
  docs/web-development/reactjs.md
  docs/web-development/vuejs.md
Labels: PR: unreviewed

#45 add: go source links
  docs/programming-languages/go.md
Labels: PR: reviewed-approved

#47 Deleted unused tasks in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#52 feat: split the links found in front-end category to CSS and JS categories
  docs/web-development/css.md
  docs/web-development/front-end.md
  docs/web-development/javascript.md
Labels: PR: unreviewed

#51 Simple is better than complex linki eklendi
  docs/web-development/django.md
Labels: PR: reviewed-approved

#50 Update matlab.md
  docs/programming-languages/matlab.md
Labels: PR: reviewed-approved

#48 add: gnu/linux source links
  docs/operating-systems/gnu-linux.md
Labels: PR: reviewed-approved

#58 Bi kaç tane yeni django tutorial linki
  docs/web-development/django.md
Labels: PR: reviewed-approved

#57 Update Python
  docs/programming-languages/python.md
Labels: PR: unreviewed

#59 Update matlab.md
  docs/programming-languages/matlab.md
Labels: PR: reviewed-approved

#61 docs: add new categories
  docs/programming-languages/computer-science.md
  docs/web-development/back-end.md
  docusaurus.config.js
  sidebars.js
Labels: PR: unreviewed

#60 docs: add Django links
  docs/web-development/django.md
Labels: PR: reviewed-approved

#64 docs: add HTML links
  docs/web-development/html.md
Labels: PR: reviewed-approved

#65 docs: add Django links
  docs/web-development/django.md
Labels: PR: reviewed-approved

#66 docs: add README.md and Code Owners
  .github/CODEOWNERS
  README.md
  src/pages/index.js
Labels: PR: unreviewed

#67 [#55] add: favicon.ico
  static/img/favicon.ico
Labels: PR: reviewed-approved

#68 [#55] replace: mountain illustration
  docs/graphic-design/general-design.md
  static/img/undraw_docusaurus_mountain.svg
Labels: PR: unreviewed

#70 gnu/linux nedir?entry level resource added
  docs/operating-systems/gnu-linux.md
Labels: PR: reviewed-approved

#71 docs: add HTML links
  docs/web-development/html.md
Labels: PR: reviewed-approved

#73 docs: added Django links and updated a link title
  docs/web-development/django.md
Labels: PR: reviewed-approved

#72 update gnu-linux.md
  docs/operating-systems/gnu-linux.md
Labels: PR: reviewed-approved

#76 [#75] feat: set dev branch for merging PRs
  docusaurus.config.js
Labels: PR: unreviewed

#77 Changes done on README and PR Template
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: PR: unreviewed

#74 docs: add Python links
  docs/programming-languages/python.md
Labels: PR: reviewed-approved

#78 docs: add Arduino tutorial links
  docs/embedded-systems/arduino.md
Labels: PR: reviewed-approved

#79 createnewcategory
  docs/operating-systems/other.md
  sidebars.js
Labels: PR: reviewed-approved

#81 new category
  docs/development-tools/vim.md
  sidebars.js
Labels: PR: reviewed-approved

#82 Merging to Main Branch
  docs/development-tools/vim.md
  docs/embedded-systems/arduino.md
  docs/graphic-design/general-design.md
  docs/graphic-design/photo-and-video.md
  docs/graphic-design/ui-ux-design.md
  docs/operating-systems/macos.md
  docs/programming-languages/c.md
  docs/programming-languages/cplusplus.md
  docs/programming-languages/go.md
  docs/programming-languages/python.md
  docs/programming-languages/ruby.md
  sidebars.js
Labels: PR: reviewed-approved

#83 Dev
  docs/development-tools/vim.md
  docs/operating-systems/gnu-linux.md
  docs/operating-systems/other.md
  docs/programming-languages/cplusplus.md
  docs/programming-languages/go.md
  docs/programming-languages/matlab.md
  docs/programming-languages/python.md
  docs/web-development/front-end.md
  docs/web-development/html.md
  docs/web-development/javascript.md
  docs/web-development/nodejs.md
  docs/web-development/reactjs.md
Labels: PR: unreviewed

#84 [ #55] feat: add banner and change button styling
  src/pages/index.js
  src/pages/styles.module.css
  static/gif/source-pocket-banner.gif
Labels: PR: unreviewed, enhancement

#85 docs: add Python links
  docs/programming-languages/python.md
Labels: PR: reviewed-approved

#86 docs: add Flask links
  docs/web-development/flask.md
Labels: PR: reviewed-approved

#87 docs: add Arduino links
  docs/embedded-systems/arduino.md
Labels: PR: reviewed-approved

#89 docs: add link
  docs/programming-languages/computer-science.md
Labels: PR: reviewed-approved

#88 docs: add Raspberry pi links
  docs/embedded-systems/raspberry-pi.md
Labels: PR: reviewed-approved

#90 docs: add Java links
  docs/programming-languages/java.md
Labels: PR: reviewed-approved

#91 docs: add a new Python link
  docs/programming-languages/python.md
Labels: PR: reviewed-approved

#93 docs: add CSS links
  docs/web-development/css.md
Labels: PR: reviewed-approved

#94 docs: add HTML link
  docs/web-development/html.md
Labels: PR: reviewed-approved

#95 docs: add MySQL link
  docs/databases/mysql.md
Labels: PR: unreviewed

#92 added new source
  docs/development-tools/vim.md
Labels: PR: reviewed-approved

#96 docs: add JavaScript links
  docs/web-development/javascript.md
Labels: PR: reviewed-approved

#97 docs: add Wordpress link
  docs/web-development/wordpress.md
Labels: PR: unreviewed

#98 docs: add VueJS links
  docs/web-development/vuejs.md
Labels: PR: reviewed-approved

#99 docs: add HTML link
  docs/web-development/html.md
Labels: PR: reviewed-approved

#100 docs: add Git links
  docs/development-tools/git.md
Labels: PR: reviewed-approved

#101 Update c.md
  docs/programming-languages/c.md
Labels: PR: reviewed-approved

#102 merging to main
  README.md
  docs/databases/mysql.md
  docs/development-tools/git.md
  docs/development-tools/vim.md
  docs/embedded-systems/arduino.md
  docs/embedded-systems/raspberry-pi.md
  docs/programming-languages/c.md
  docs/programming-languages/computer-science.md
  docs/programming-languages/java.md
  docs/programming-languages/python.md
  docs/web-development/css.md
  docs/web-development/flask.md
  docs/web-development/html.md
  docs/web-development/javascript.md
  docs/web-development/vuejs.md
  docs/web-development/wordpress.md
  src/pages/index.js
  static/gif/source-pocket-readme.gif
Labels: PR: unreviewed

#103 docs: added Flask links
  docs/web-development/flask.md
Labels: PR: reviewed-approved

#104 docs: add links to android
  docs/mobile-development/android.md
Labels: PR: reviewed-approved

#105 docs: add link to computer science
  docs/programming-languages/computer-science.md
Labels: PR: reviewed-approved

#106 docs: add link to android
  docs/mobile-development/android.md
Labels: PR: reviewed-approved

#107 docs: add link to Android
  docs/mobile-development/android.md
Labels: PR: reviewed-approved

#108 docs: add link to android
  docs/mobile-development/android.md
Labels: PR: reviewed-approved

#110 Updated Begginer and Intermediate
  docs/web-development/wordpress.md
Labels: PR: reviewed-approved

#109 docs: add link to java
  docs/programming-languages/java.md
Labels: PR: reviewed-approved

#111 Ready for Deployment
  README.md
  docs/mobile-development/android.md
  docs/programming-languages/computer-science.md
  docs/programming-languages/java.md
  docs/style-guide.md
  docs/web-development/flask.md
  docs/web-development/wordpress.md
Labels: PR: unreviewed, enhancement

#112 Update javascript.md
  docs/web-development/javascript.md
Labels: PR: reviewed-approved

#113 docs: Youtube videos&playlists about Deep Learning
  docs/artificial-intelligence/deep-learning.md
Labels: PR: reviewed-approved

#114 Ready to Deploy 🛳
  docs/artificial-intelligence/deep-learning.md
  docs/web-development/javascript.md
Labels: PR: unreviewed

#117 docs: added some guides and examples about Python
  docs/programming-languages/python.md
Labels: PR: reviewed-approved
