Repository Source-Pocket/source-pocket, pull requests merged in 2021-03, with the labels that each got.

#115 docs: text&video sources added about Deep Learning
  docs/artificial-intelligence/deep-learning.md
Labels: PR: reviewed-approved

#116 docs: added online sources&courses about ML
  docs/artificial-intelligence/machine-learning.md
Labels: PR: reviewed-approved

#118 docs: added online sources&courses about GoLang
  docs/programming-languages/go.md
Labels: PR: reviewed-approved

#119 Update python.md
  docs/programming-languages/python.md
Labels: PR: reviewed-approved

#120 add link to android
  docs/mobile-development/android.md
Labels: PR: reviewed-approved

#123 docs: add go source links
  docs/programming-languages/go.md
Labels: PR: reviewed-approved

#124 Added some official Rust language resource links.
  docs/programming-languages/rust.md
Labels: PR: reviewed-approved

#125 docs: added Django link
  docs/web-development/django.md
Labels: PR: reviewed-approved

#121 docs: add new links to assembly
  docs/programming-languages/assembly.md
Labels: PR: reviewed-approved

#122 docs: add new links to other os
  docs/operating-systems/other.md
Labels: PR: reviewed-approved

#126 docs: add JQuery links
  docs/web-development/jquery.md
Labels: PR: reviewed-approved

#127 Added C resource links.
  docs/programming-languages/c.md
Labels: PR: reviewed-approved

#128 Added C++ resource links.
  docs/programming-languages/cplusplus.md
Labels: PR: unreviewed

#129 docs: add go source link
  docs/programming-languages/go.md
Labels: PR: reviewed-approved

#130 Ready to merge
  .github/CODEOWNERS
  docs/artificial-intelligence/deep-learning.md
  docs/artificial-intelligence/machine-learning.md
  docs/mobile-development/android.md
  docs/operating-systems/other.md
  docs/programming-languages/assembly.md
  docs/programming-languages/c.md
  docs/programming-languages/cplusplus.md
  docs/programming-languages/go.md
  docs/programming-languages/python.md
  docs/programming-languages/rust.md
  docs/web-development/django.md
  docs/web-development/jquery.md
  package.json
  yarn.lock
Labels: PR: unreviewed, dev-to-main

#131 Added more resource links for Rust.
  docs/programming-languages/rust.md
Labels: PR: unreviewed

#132 Added The Linux Kernel Documentation.
  docs/operating-systems/gnu-linux.md
Labels: PR: reviewed-approved

#133 Update cplusplus.md
  docs/programming-languages/cplusplus.md
Labels: PR: reviewed-approved

#134 Links are updated w/ Content
  docs/web-development/wordpress.md
Labels: PR: reviewed-approved

#135 docs: a few words corrected
  docs/programming-languages/python.md
Labels: PR: reviewed-approved

#136 add link to kotlin
  docs/programming-languages/kotlin.md
Labels: PR: partially-approved

#139 docs: add TypeScript link
  docs/web-development/typescript.md
Labels: PR: partially-approved

#138 docs: added code owners
  README.md
Labels: PR: partially-approved

#140 New resources added on NodeJS, MongoDB, Docker, Vim, TypeScript, GoLang
  docs/databases/mongodb.md
  docs/development-tools/docker.md
  docs/development-tools/vim.md
  docs/programming-languages/go.md
  docs/web-development/nodejs.md
  docs/web-development/typescript.md
Labels: PR: partially-approved

#141 docs: js, vuejs and react js links
  docs/web-development/javascript.md
  docs/web-development/reactjs.md
  docs/web-development/vuejs.md
Labels: PR: partially-approved

#144 docs: fixed some words
  docs/web-development/javascript.md
Labels: PR: partially-approved

#145 docs: fixed some words
  docs/web-development/vuejs.md
Labels: PR: partially-approved

#146 docs: fixed some words
  docs/web-development/reactjs.md
Labels: PR: partially-approved

#147 docs: add Git links
  docs/development-tools/git.md
Labels: PR: partially-approved

#150 Ready to Deploy 🚢
  .github/CODEOWNERS
  README.md
  docs/databases/mongodb.md
  docs/development-tools/docker.md
  docs/development-tools/git.md
  docs/development-tools/vim.md
  docs/programming-languages/go.md
  docs/programming-languages/kotlin.md
  docs/web-development/javascript.md
  docs/web-development/nodejs.md
  docs/web-development/reactjs.md
  docs/web-development/typescript.md
  docs/web-development/vuejs.md
  static/humans.txt
Labels: PR: unreviewed, dev-to-main, documentation, enhancement

#151 Create denojs.md
  docs/web-development/denojs.md
  docs/web-development/php.md
  docs/web-development/ruby-on-rails.md
  sidebars.js
Labels: PR: partially-approved

#152 doc: add new links to assembly.md
  docs/programming-languages/assembly.md
Labels: PR: partially-approved

#153 doc: new links added to assembly.md
  docs/programming-languages/assembly.md
Labels: PR: partially-approved

#154 docs: add new link to Git
  docs/development-tools/git.md
Labels: PR: partially-approved

#155 docs: added online sources&courses about GoLang
  docs/programming-languages/go.md
Labels: PR: unreviewed

#156 Revert "docs: added online sources&courses about GoLang"
  docs/programming-languages/go.md
Labels: PR: unreviewed

#157 Dev to Main
  docs/development-tools/git.md
  docs/programming-languages/assembly.md
  docs/web-development/denojs.md
  docs/web-development/php.md
  docs/web-development/ruby-on-rails.md
  package.json
  sidebars.js
  yarn.lock
Labels: PR: unreviewed, dev-to-main, documentation

#158 docs: update go.md
  docs/programming-languages/go.md
Labels: PR: partially-approved

#159 docs: add http statuses list link
  docs/web-development/hosting-and-servers.md
Labels: PR: partially-approved

#160 docs: add Linux Shell Tips website link
  docs/operating-systems/gnu-linux.md
Labels: PR: unreviewed

#161 docs: add git exercises website link
  docs/development-tools/git.md
Labels: PR: partially-approved

#162 docs: added online sources&courses about GoLang
  docs/programming-languages/go.md
Labels: PR: partially-approved

#163 Dev to Main 🚢
  docs/development-tools/git.md
  docs/operating-systems/gnu-linux.md
  docs/programming-languages/go.md
  docs/web-development/hosting-and-servers.md
  docs/web-development/vuejs.md
Labels: PR: unreviewed, dev-to-main

#164 docs: add Go Database SQL website
  docs/programming-languages/go.md
Labels: PR: partially-approved

#165 Dev
  docs/programming-languages/go.md
  package.json
  yarn.lock
Labels: PR: unreviewed, bug, dev-to-main

#166 Update csharp.md
  docs/programming-languages/csharp.md
Labels: PR: partially-approved

#167 docs: edit docker links and add new one
  docs/development-tools/docker.md
Labels: PR: partially-approved
