Repository Source-Pocket/source-pocket, pull requests merged in 2021-05, with the labels that each got.

#183 Update csharp.md
  docs/programming-languages/csharp.md
Labels: PR: partially-approved

#182 Update python.md
  docs/programming-languages/python.md
Labels: PR: unreviewed

#186 Update README.md
  README.md
Labels: PR: reviewed-approved

#187 Update python.md
  docs/programming-languages/python.md
Labels: PR: partially-approved

#188 Update reactnative.md
  docs/mobile-development/reactnative.md
Labels: PR: partially-approved

#190 asp.net MVC için crash course
  docs/web-development/asp-net-mvc.md
Labels: PR: unreviewed

#191 Dev to Main 🚢🚢
  README.md
  docs/mobile-development/reactnative.md
  docs/programming-languages/csharp.md
  docs/programming-languages/python.md
  docs/web-development/asp-net-mvc.md
Labels: PR: unreviewed, dev-to-main, documentation

#194 add: link
  docs/web-development/front-end.md
Labels: PR: partially-approved

#195 docs: added illustrations link.
  docs/graphic-design/illustrations.md
Labels: PR: unreviewed

#196 Resources for Many Section has been added.
  docs/databases/mongodb.md
  docs/development-tools/git.md
  docs/mobile-development/flutter.md
  docs/mobile-development/reactnative.md
  docs/web-development/denojs.md
  docs/web-development/django.md
  docs/web-development/laravel.md
  docs/web-development/nodejs.md
  docs/web-development/reactjs.md
  docs/web-development/vuejs.md
Labels: PR: partially-approved

#198 Update html.md
  docs/web-development/html.md
Labels: PR: partially-approved

#200 Update front-end.md
  docs/web-development/front-end.md
Labels: PR: partially-approved

#199 Added postgresdb resources and Created kubernetes page
  docs/databases/postgresdb.md
  docs/development-tools/kubernetes.md
  docs/programming-languages/python.md
  docs/web-development/java-spring.md
  docs/web-development/javascript.md
  docs/web-development/reactjs.md
  sidebars.js
Labels: PR: partially-approved, documentation, enhancement

#201 Dev to Main 🚢🚢
  docs/databases/mongodb.md
  docs/databases/postgresdb.md
  docs/development-tools/git.md
  docs/development-tools/kubernetes.md
  docs/graphic-design/illustrations.md
  docs/mobile-development/flutter.md
  docs/mobile-development/reactnative.md
  docs/programming-languages/python.md
  docs/web-development/denojs.md
  docs/web-development/django.md
  docs/web-development/front-end.md
  docs/web-development/html.md
  docs/web-development/java-spring.md
  docs/web-development/javascript.md
  docs/web-development/laravel.md
  docs/web-development/nodejs.md
  docs/web-development/reactjs.md
  docs/web-development/vuejs.md
  docusaurus.config.js
  package.json
  sidebars.js
  yarn.lock
Labels: PR: unreviewed, dev-to-main, documentation, enhancement

#202 Resources for Many Section has been added
  docs/artificial-intelligence/artificial-intelligence.md
  docs/artificial-intelligence/deep-learning.md
  docs/artificial-intelligence/machine-learning.md
  docs/data-science/big-data.md
  docs/data-science/statistical-learning.md
  docs/databases/postgresdb.md
  docs/development-tools/aws.md
  docs/development-tools/azure.md
  docs/development-tools/kubernetes.md
  docs/programming-languages/python.md
Labels: PR: partially-approved
